masking_rules:
  name: 'Z' * length
  address: nullify city_state
  phone: '999-999-9999'
  ssn: '999-99-9999'
  financial_details: nullify
  dob: '01/01/1099'

tables:
  - name: customers
    columns:
      name: name
      address: address
      phone: phone_number
      ssn: ssn
      financial: financial_details
      dob: date_of_birth
    relationships: []