oracle:
  host: your_oracle_host
  port: 1521
  service_name: your_service_name
  user: your_username
  password: your_password

snowflake:
  account: your_account
  user: your_username
  password: your_password
  warehouse: your_warehouse
  database: your_database
  schema: your_schema